spring.application.name=SmartNotesManager
spring.data.mongodb.uri=${SMART_NOTES_MONGO_URI}
logging.level.org.springframework.data.mongodb=DEBUG
spring.data.mongodb.database=smartnotesmanager
spring.data.mongodb.auto-index-creation=true